const notificationStyles = {
  danger: [
    'text-center',
    'font-serif',
    'text-lg',
    'font-bold',
    'py-3',
    'px-5',
    'mb-4',
    'bg-red-100',
    'text-red-900',
    'text-sm',
    'rounded-md',
    'border',
    'border-red-200',
  ].join(' '),
  success: [
    'text-center',
    'font-serif',
    'text-lg',
    'font-bold',
    'py-3',
    'px-5',
    'mb-4',
    'bg-green-100',
    'text-green-900',
    'text-sm',
    'rounded-md',
    'border',
    'border-green-200',
  ].join(' '),
  warning: [
    'text-center',
    'font-serif',
    'text-lg',
    'font-bold',
    'py-3',
    'px-5',
    'mb-4',
    'bg-yellow-100',
    'text-yellow-900',
    'text-sm',
    'rounded-md',
    'border',
    'border-yellow-200',
  ].join(' '),
  info: [
    'text-center',
    'font-serif',
    'text-lg',
    'font-bold',
    'py-3',
    'px-5',
    'mb-4',
    'bg-blue-100',
    'text-blue-900',
    'text-sm',
    'rounded-md',
    'border',
    'border-blue-200',
  ].join(' '),
};

export default notificationStyles;
