const createPostStyles = {
  header: [
    'pt-16',
    'text-center',
    'text-4xl',
    'text-gray-300',
    'font-serif',
    'font-bold',
  ].join(' '),
  main: ['grid', 'min-h-screen', 'place-items-center'].join(' '),
  box: [
    'w-11/12',
    'p-12',
    'bg-gray-700',
    'sm:w-8/12',
    'md:w-1/2',
    'lg:w-5/12',
    'rounded-lg',
    'shadow-lg',
  ].join(' '),
  heading: ['text-xl', 'font-semibold', 'text-white'].join(' '),
  label: [
    'block',
    'mt-2',
    'text-gray-300',
    'font-serif',
    'text-lg',
    'font-bold',
  ].join(' '),
  input: [
    'block',
    'w-full',
    'p-3',
    'mt-2',
    'text-gray-700',
    'bg-gray-200',
    'appearance-none',
    'focus:outline-none',
    'focus:bg-gray-300',
    'focus:shadow-inner',
    'font-serif',
  ].join(' '),
  submit: [
    'w-full',
    'py-3',
    'mt-6',
    'text-gray-300',
    'font-bold',
    'rounded-lg',
    'shadow-lg',
    'bg-gray-600',
    'hover:bg-gray-800',
    'hover:text-gray-400',
    'font-serif',
    'text-lg',
  ].join(' '),
  div: [
    'flex',
    'justify-evenly',
    'block w-full',
    'p-3',
    'mt-2',
    'text-gray-700',
    'bg-gray-200',
    'appearance-none',
    'focus:outline-none',
    'focus:bg-gray-300',
    'focus:shadow-inner',
    'font-serif',
  ].join(' '),
  error: ['text-red-500', 'font-semibold', 'pt-2'].join(' '),
};

export default createPostStyles;
